Lab2
OstrovskyAndriy/labs pull request #2
Opened 2023-09-11 13:53 UTC by OstrovskyAndriy

2023-09-20 13:40 UTC, RuslanSlobodian requested changes

2023-09-20 13:40 UTC, RuslanSlobodian commented on lab2/Student.java
> +
Не виконано перше завдання:
1. Створити проект, що складає... **Кожний клас повинен бути розміщений у окремому пакеті.**

2023-09-20 13:40 UTC, RuslanSlobodian commented on lab2/Main.java
> +public class Main {
Не повністю виконано 2 завдання:
2. В основному класі програми (тобто Main) визначити метод, що
створює масив об'єктів класу згідно варіанту та заповнює його тестовими
даними.

2023-09-20 13:40 UTC, RuslanSlobodian commented on lab2/Main.java
> +
Не виконано 3 завдання:
3. Визначити методи, з допомогою який можна вивести елементи масиву
чи дані відповідно до варіанту завдання. Для кожного критерію створити
окремий метод.

2023-09-21 11:37 UTC, RuslanSlobodian requested changes

2023-09-21 11:37 UTC, RuslanSlobodian commented on lab2/Main.java
> +    public static final void printStudentsBornAftet2000(Student[]students){
Даний метод мав виводити список студентів, які народились після заданого року, 
тобто рік повинен задаватись параметром.

2023-09-21 11:37 UTC, RuslanSlobodian commented on lab2/Main.java
> +    public static final void printStudents(Student[] students){
Даний метод має виводити список студентів факультету, який має задаватись параметром методу
Не потрібно хардкодити

2023-09-21 12:04 UTC, RuslanSlobodian approved these changes, later dismissed

2023-09-21 12:05 UTC, RuslanSlobodian approved these changes

2023-09-21 12:06 UTC, RuslanSlobodian approved these changes

2023-09-21 12:08 UTC, RuslanSlobodian submitted a review, later dismissed

2023-09-21 12:11 UTC, RuslanSlobodian submitted a review, later dismissed

2023-09-21 13:09 UTC, RuslanSlobodian submitted a review, later dismissed

2023-09-21 13:34 UTC, RomeoLeyn submitted a review, later dismissed

2023-09-21 13:44 UTC, closed without merging